version: "3.9"
services:
    client:
      image: client:init
      build:
        context: .
        dockerfile: dev.dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - server
      volumes:
        - .:/client/
        - client-node-modules:/client/node_modules
      networks:
        - frontend

    server:
      image: server:init
      build:
        context: server
        dockerfile: dev.dockerfile
      ports:
        - "3001:3001"
      environment:
        - SECRET_TOKEN=TESTTESTTEST
        - MONGODB_CONNSTRING=mongodb://MongoAdmin:DevelopmentOnlyPass321@mongo:27017/app?retryWrites=true&w=majority&authSource=admin
      depends_on:
        - mongodb
      volumes:
        - ./server:/server
      command: sh /server/start.sh
      links:
        - "mongodb:mongo"
      networks:
        - backend
        - frontend

    mongodb:
      image: mongo:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=MongoAdmin
        - MONGO_INITDB_ROOT_PASSWORD=DevelopmentOnlyPass321
      ports:
        - "27017:27017"
      volumes:
        - ./mdb-data:/data/db
      networks:
        - backend

volumes:
  client-node-modules:

networks:
  frontend:
  backend: